### ISSUE TITLE
Adding a category header

### ISSUE THREAD

**Issue by paulrosen** [CodeAwhile/wp-sendgrid#1]
Thanks for your simple-to-use plug in! The only thing I haven't been able to figure out how to do is to add a category to the mail so that I can sort multiple wordpress sites on the sendgrid statistics page.

Their documentation says to add this mail header (which I've been able to do in my Rails app like this):

```
"X-SMTPAPI" => "{\"category\": \"My Site\"}"
```

Just to see if I could get this to work, I've tried hacking wp-sendgrid/includes/wp-mail.php in various ways:

```
$headers['category'] = "test1";
$args['category'] = "test2";
$args["X-SMTPAPI"] = '{"category": ["test3"]}';
$headers["X-SMTPAPI"] = '{"category": ["test4"]}';
```

But I evidently don't understand something basic. Is there a built in way to add the category that I'm missing? If not, can you help me get the syntax right for adding the category? Would you consider adding that feature to the plugin in the next version?

Thanks!

**Comment by itsananderson** [comment]
I think you might be able to add this header when you call wp_mail(), since you can include a header string. I'll try to test that out this evening and see if I can come up with a working example.

**Comment by itsananderson** [comment]
Confirmed that this is not currently supported (or at least overly difficult). I've added a new branch, which adds a filter to allow X-SMTPAPI headers to be added.

If you go to this URL, you should be able to download a [zip file](https://github.com/CodeAwhile/wp-sendgrid/archive/xsmtpapi.zip) with the updated branch. The branch is located here: https://github.com/CodeAwhile/wp-sendgrid/tree/xsmtpapi

You can then use something like the following code to add a category to all emails. As a quick test, put this code in a mu-plugin and then trigger an email. Make sure you enable the new version of WP SendGrid first, or else this won't do anything.

``` php
<?php

class XSmtpApi_Test {
    public static function start() {
        add_filter( 'wp_sendgrid_xsmtpapi', array( __CLASS__, 'set_cat' ) );
    }

    public static function set_cat( $xsmtpapi ) {
        $xsmtpapi['category'] = 'Test'; // Change this to the desired category
        return $xsmtpapi;
    }
}

XSmtpApi_Test::start();
```

You should be able to use the same filter functionality to add other X-SMTPAPI headers as well.

Any chance you could grab the xsmtpapi branch version and test it out? If you can get it to work without too much hassle, I can merge it into the master branch and release a new version.

**Comment by paulrosen** [comment]
First, thanks for your quick response!

I did try the new version on the plugin, and created a new plugin with the above code, and it did work.

I have a usability request, though. The sites I'm setting up (a group of 6 related ones) will be administered by the end user and I'd like them to be able to enter the category value themselves. Instead of creating a second page for SendGrid category settings, it seems like it would make more sense to have this value in your settings page.

And, while I'm asking, the same is true for the `wp_mail_from` and `wp_mail_from_name` filters. I envision that if the filter is present and returned a non-blank, that is used. If it isn't, then the value in the settings is used. If that is blank, then the fallback method you currently have is used.

Thanks,
Paul

**Comment by itsananderson** [comment]
I think there are two ways to approach this.

The first approach, which I'd prefer, is to make WP SendGrid more extensible (let plugins hook into the settings page etc.), then write an extension plugin that adds those new fields. The advantage of this approach is that it keeps the core plugin very lightweight, by not adding features that aren't needed by everyone. The disadvantage is that it would require installing an extra plugin on any site that needs the extra functionality.

The second approach is to simply add the new features to WP SendGrid. The advantage is that you won't have to install an extra plugin. The disadvantage is that it adds extra fields to the plugin configuration page, which might not be used by most people.

What do you think? If the "two plugin" approach would work for you, I can write the second plugin once I've made the core plugin more extensible. If having to install two plugins on each site seems like too much hassle, I'm not opposed to going with the second approach.

**Comment by paulrosen** [comment]
My preference is one plugin because I don't want to explain to users that they go to one settings page to enter their account settings for sendgrid and another settings page to enter the category and the email that they want the mail to appear to be from.

I can work either way, though.

One other thing to keep in mind is there are a class of WP administrators like me for whom PHP is not their first language, or are not really developers. It's pretty confusing figuring out what the signature of the filter functions are. Having an option is really useful.

Also, while I know small modular plugins are good programming practice, just from an administrative standpoint the less you have to explain to your clients the better.

**Comment by itsananderson** [comment]
I explained the first option poorly. If I went with the two plugin approach, I'd have the second plugin inject the options into the same settings page, so you could go to the same page to enter all of your SendGrid settings. Would that work?

**Comment by paulrosen** [comment]
Sorry, I didn't read that closely enough. That certainly works for my client, because they only see one page to take care of everything related to email.

It not that much more work for me to install two plugins instead of one (of course for the 6 sites I'm setting up, that's 12 plugins instead of 6.) I suppose they will both be updated at the same time to keep them in sync.

I haven't seen that paradigm used in WP, though.

Another way to keep that settings page simple is to use the "Screen Options" type control, that slides down and allows the administrator to select which options are visible using checkboxes. In fact, you could just show it for the admin user and not for the editor user. That would be good even for the current options, because I don't want a user changing the "Rest API" choice then calling me to straighten it out.

But, either way is fine, really -- I'm hoping to get the site ready for testing in the next couple days. I have enough info now to hack the current plugin while waiting for your update.

**Comment by itsananderson** [comment]
Ok. I finally had a chance to finish the rewrite. Currently, version 2.0.1 on the WordPress.org repository can be extended to include categories.

I wrote up two new plugins that you might find useful. The first adds a category field to the SendGrid settings page, and the second hides the SendGrid "Account Settings" section.

https://github.com/CodeAwhile/wp-sendgrid-categories
https://github.com/CodeAwhile/wp-sendgrid-hide-settings

I haven't gotten these plugins on the WordPress.org repo, and I still haven't decide whether to do so, but you can at least clone them from GitHub.

Once you've configured your customer's sites, you can enable the "WP SendGrid Hide Settings" plugin to keep them from accidentally modifying their site settings.

Both of those new plugins are just a single PHP file (plus readme files etc.), so you can also just drop them in the mu-plugins folder for a minimum hassle installation. Here's the Must Use Plugins article, just in case.

http://codex.wordpress.org/Must_Use_Plugins
